[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:neo4j]
command=/startup/docker-entrypoint.sh neo4j
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/neo4j.err.log
stdout_logfile=/var/log/supervisor/neo4j.out.log
user=neo4j
environment=HOME="/var/lib/neo4j",USER="neo4j"

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/nginx.err.log
stdout_logfile=/var/log/supervisor/nginx.out.log
startretries=3
startsecs=10

